# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-15 02:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Business',
            fields=[
                ('business_id', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=20)),
                ('state', models.CharField(max_length=10)),
                ('stars', models.FloatField()),
                ('categories', models.CharField(max_length=200)),
                ('price', models.IntegerField(null=True)),
                ('restaurant_stars', models.FloatField(null=True)),
                ('bar_stars', models.FloatField(null=True)),
                ('food_stars', models.FloatField(null=True)),
                ('cafe_stars', models.FloatField(null=True)),
                ('movie_theater_stars', models.FloatField(null=True)),
                ('lodging_stars', models.FloatField(null=True)),
                ('night_club_stars', models.FloatField(null=True)),
                ('parking', models.IntegerField(null=True)),
                ('bus_station', models.IntegerField(null=True)),
                ('transit_station', models.IntegerField(null=True)),
                ('university', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stars', models.IntegerField(default=0)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='demo.Business')),
            ],
        ),
        migrations.RenameField(
            model_name='user',
            old_name='user_email',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='user_password',
            new_name='password',
        ),
        migrations.RemoveField(
            model_name='user',
            name='id',
        ),
        migrations.AlterField(
            model_name='user',
            name='user_id',
            field=models.CharField(max_length=32, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='rating',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='demo.User'),
        ),
    ]
